### PR TITLE
fail extreme goal check when no arithmetic change

### PR DESCRIPTION
**Pull request by benhawkinsicon**
Proposed fix for https://github.com/caesuric/mountain-goap/issues/22

### CODE REVIEW

**Comment by benhawkinsicon** [comment]
Obviously it can go either way between `isHigherThan` or `isLessThanOrEqualTo`, I think the crux of it was one of the methods being swapped

**Comment by UhGoomba** [comment]
hey, I appreciate this!

**Comment by caesuric** [comment]
💯%, this was an issue. Thank you for fixing this!!

**Review by caesuric — APPROVED** [review]
Looks good to me, everything tested and works fine in all of the demos.

**Pull request merged**
